### ISSUE TITLE
Learning Dataset Information

### ISSUE THREAD

**Issue by wongchit** [xxyux/Fine-tuning-LLM-with-2-4-sparse#1]
Hello, sorry to bother you. I am also researching using LLM for sentiment classification tasks. Excuse me, is it using the IMDB dataset of the huggingface? May I know the information about the IMDB dataset you are using? If possible, thank you very much!

**Comment by xxyux** [comment]
It's my honor to receive your message. 
Imdb is an open dataset in Huggingface, url is https://huggingface.co/datasets/imdb.

**Comment by wongchit** [comment]
> It's my honor to receive your message. Imdb is an open dataset in Huggingface, url is https://huggingface.co/datasets/imdb.

Understood, thank you!
